import { config } from 'dotenv'

config({ path: '.env' })

export const {
  PORT,
  LOG_DIR,
  FRONTEND_URL,
  NODE_ENV,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRES_SECONDS,
  IDLE_TIMEOUT_SECONDS,
  COOKIE_DOMAIN,
  // Keycloak (IAM Universitas) — OIDC Authorization Code + PKCE
  KEYCLOAK_ISSUER_URL,
  KEYCLOAK_CLIENT_ID,
  KEYCLOAK_CLIENT_SECRET,
  KEYCLOAK_REDIRECT_URI
} = process.env
