// THE Impact Rankings 2026 — SDG Indicator Configuration
// Source: Times Higher Education Impact Rankings methodology

export interface SubQuestion {
  index: number;
  label: string;
  maxPoints: number;
  options: { value: number; label: string }[];
}

export interface QuantMetric {
  key: string;
  label: string;
  unit: string;
}

export interface SdgIndicator {
  code: string;
  label: string;
  type: "BIBLIOMETRIC" | "QUANTITATIVE" | "QUALITATIVE";
  weightInSdg: number;
  maxScore?: number;
  subQuestions?: SubQuestion[];
  metrics?: QuantMetric[];
}

export interface SdgConfig {
  number: number;
  title: string;
  emoji: string;
  color: string;
  mandatory: boolean;
  indicators: SdgIndicator[];
}

export const STD_3PT: SubQuestion[] = [
  { index: 0, label: "Keberadaan / Existence", maxPoints: 1, options: [{ value: 1, label: "Ya" }, { value: 0, label: "Tidak" }] },
  { index: 1, label: "Bukti menjawab pertanyaan", maxPoints: 1, options: [{ value: 1, label: "Menjawab sepenuhnya" }, { value: 0.5, label: "Menjawab sebagian" }, { value: 0, label: "Tidak menjawab / tidak ada" }] },
  { index: 2, label: "Bukti tersedia publik", maxPoints: 1, options: [{ value: 1, label: "Ya, publik" }, { value: 0, label: "Tidak" }] },
];

export const STD_4PT: SubQuestion[] = [
  { index: 0, label: "Keberadaan kebijakan", maxPoints: 1, options: [{ value: 1, label: "Ya" }, { value: 0, label: "Tidak" }] },
  { index: 1, label: "Bukti menjawab pertanyaan", maxPoints: 1, options: [{ value: 1, label: "Menjawab sepenuhnya" }, { value: 0.5, label: "Menjawab sebagian" }, { value: 0, label: "Tidak menjawab / tidak ada" }] },
  { index: 2, label: "Bukti tersedia publik", maxPoints: 1, options: [{ value: 1, label: "Ya, publik" }, { value: 0, label: "Tidak" }] },
  { index: 3, label: "Kebijakan dibuat/diperbarui 2021-2025", maxPoints: 1, options: [{ value: 1, label: "Ya" }, { value: 0, label: "Tidak" }] },
];

export const QUAL_QUESTIONS: Record<string, string> = {
  "1.3.1": "Apakah Universitas memiliki target untuk menerima mahasiswa yang termasuk dalam kelompok pendapatan rumah tangga 20% terbawah (atau target yang lebih ketat)?",
  "1.3.2": "Apakah Universitas memiliki target kelulusan/penyelesaian studi untuk mahasiswa yang termasuk dalam kelompok pendapatan rumah tangga 20% terbawah (atau target yang lebih ketat)?",
  "1.3.3": "Apakah Universitas menyediakan dukungan (misalnya makanan, perumahan, transportasi, layanan hukum) untuk mahasiswa dari keluarga berpenghasilan rendah agar mereka dapat menyelesaikan kuliah?",
  "1.3.4": "Apakah Universitas memiliki program atau inisiatif untuk membantu mahasiswa yang termasuk dalam kelompok pendapatan rumah tangga 20% terbawah (atau target yang lebih ketat) di negara ini agar berhasil menyelesaikan studi mereka?",
  "1.3.5": "Apakah Universitas memiliki skema untuk mendukung mahasiswa ekonomi lemah dari negara berpenghasilan rendah atau menengah ke bawah (misalnya menawarkan pendidikan gratis, hibah)?",
  "1.4.1": "Apakah Universitas menyediakan bantuan di komunitas lokal yang mendukung dimulainya bisnis yang berkelanjutan secara finansial dan sosial melalui pendidikan atau sumber daya yang relevan?",
  "1.4.2": "Apakah Universitas menyediakan bantuan keuangan kepada komunitas lokal yang membantu memulai bisnis yang berkelanjutan secara finansial dan sosial?",
  "1.4.3": "Apakah Universitas menyelenggarakan pelatihan atau program untuk meningkatkan akses ke layanan dasar untuk semua?",
  "1.4.4": "Apakah Universitas berpartisipasi dalam pembuatan kebijakan di tingkat lokal, regional, nasional dan/atau global untuk menerapkan program dan kebijakan untuk mengakhiri kemiskinan dalam semua dimensinya?",
  "2.2.1": "Apakah Universitas mengukur jumlah sampah makanan yang dihasilkan dari makanan yang disajikan?",
  "2.3.1": "Apakah Universitas memiliki program untuk mengatasi kerawanan pangan/kelaparan mahasiswa?",
  "2.3.2": "Apakah Universitas melakukan intervensi untuk mencegah atau mengurangi kelaparan di kalangan mahasiswa?",
  "2.3.3": "Apakah Universitas menyediakan pilihan makanan yang berkelanjutan kepada semua orang di kampus, termasuk makanan vegetarian dan vegan?",
  "2.3.4": "Apakah Universitas menyediakan pilihan makanan yang sehat dan terjangkau untuk semua orang di kampus?",
  "2.3.5": "Apakah Universitas menyediakan intervensi untuk mencegah atau mengurangi kelaparan di kalangan staf?",
  "2.5.1": "Apakah Universitas menyediakan akses pada keamanan pangan dan pengetahuan, keterampilan, atau teknologi pertanian dan akuakultur berkelanjutan bagi petani dan produsen pangan lokal?",
  "2.5.2": "Apakah Universitas menyediakan acara bagi petani dan produsen pangan lokal untuk saling terhubung dan mentransfer pengetahuan?",
  "2.5.3": "Apakah Universitas menyediakan akses ke fasilitas yang dimiliki (misalnya laboratorium, teknologi, stok tanaman) bagi petani dan produsen pangan lokal?",
  "2.5.4": "Apakah Universitas memprioritaskan pembelian produk dari sumber lokal yang berkelanjutan?",
  "3.3.1": "Apakah Universitas memiliki kolaborasi terkini dengan lembaga kesehatan lokal, nasional, atau global?",
  "3.3.2": "Apakah Universitas memberikan program dan proyek penjangkauan di komunitas lokal untuk meningkatkan kesehatan & kesejahteraan?",
  "3.3.3": "Apakah Universitas berbagi fasilitas olahraga dengan komunitas lokal?",
  "3.3.4": "Apakah Universitas menyediakan akses bagi mahasiswa ke layanan perawatan kesehatan seksual atau reproduksi?",
  "3.3.5": "Apakah Universitas menyediakan akses bagi mahasiswa untuk dukungan kesehatan mental?",
  "3.3.6": "Apakah Universitas memiliki kebijakan \"bebas asap rokok\"?",
  "3.3.7": "Apakah Universitas menyediakan akses bagi pegawai/staf untuk dukungan kesehatan mental?",
  "4.3.1": "Apakah Universitas menyediakan akses gratis ke sumber daya pendidikan kepada yang bukan mahasiswa UB?",
  "4.3.2": "Apakah Universitas menyelenggarakan acara di universitas yang terbuka untuk masyarakat umum?",
  "4.3.3": "Apakah Universitas menyelenggarakan acara di universitas yang terbuka untuk masyarakat umum semisal program pendidikan khusus dan/atau pelatihan/training kejuruan?",
  "4.3.4": "Apakah Universitas melakukan kegiatan pendidikan di luar kampus?",
  "4.3.5": "Apakah Universitas memiliki kebijakan yang memastikan bahwa akses ke kegiatan-kegiatan ini dapat diakses oleh semua orang?",
  "5.3.1": "Apakah Universitas secara sistematis mengukur/melacak tingkat pendaftaran dan penerimaan mahasiswa perempuan?",
  "5.3.2": "Apakah Universitas memiliki kebijakan yang membahas pendaftaran, penerimaan, dan partisipasi perempuan di Universitas?",
  "5.3.3": "Apakah Universitas menyediakan skema/akses bagi perempuan seperti misalnya pendampingan, beasiswa, atau ketentuan lainnya?",
  "5.3.4": "Apakah Universitas mendorong pendaftaran mahasiswa baru oleh perempuan dari golongan minoritas?",
  "5.6.1": "Apakah Universitas memiliki kebijakan nondiskriminasi terhadap perempuan?",
  "5.6.2": "Apakah Universitas memiliki kebijakan nondiskriminasi terhadap orang transgender?",
  "5.6.3": "Apakah Universitas memiliki kebijakan maternitas yang mendukung partisipasi perempuan?",
  "5.6.4": "Apakah Universitas memiliki fasilitas penitipan anak yang dapat diakses oleh mahasiswa?",
  "5.6.5": "Apakah Universitas memiliki fasilitas penitipan anak untuk staf?",
  "5.6.6": "Apakah Universitas memiliki skema bimbingan/mentoring untuk perempuan?",
  "5.6.7": "Apakah Universitas memiliki pengukuran/pelacakan kemungkinan kelulusan perempuan?",
  "5.6.8": "Apakah Universitas memiliki kebijakan yang melindungi bagi mereka yang melaporkan terkait diskriminasi?",
  "5.6.9": "Apakah Universitas memiliki kebijakan paternitas yang mendukung partisipasi perempuan?",
  "6.2.1": "Apakah Universitas melakukan pengukuran sumber air yang digunakan untuk keperluannya?",
  "6.3.1": "Apakah Universitas melakukan pengolahan air limbah?",
  "6.3.2": "Apakah Universitas melakukan upaya pencegahan pencemaran air?",
  "6.3.3": "Apakah Universitas menyediakan air minum secara gratis ke mahasiswa / staff / pengunjung?",
  "6.3.4": "Apakah Universitas memiliki regulasi terkait standar bangunan tertentu dalam penghematan air?",
  "6.3.5": "Apakah Universitas menanam jenis tanaman tertentu dalam upaya penghematan air?",
  "6.4.1": "Apakah Universitas memiliki peraturan untuk optimalisasi kegiatan daur ulang air?",
  "6.4.2": "Apakah Universitas melakukan pengukuran daur ulang?",
  "6.5.1": "Apakah Universitas pernah memberikan edukasi tentang pengelolaan air kepada masyarakat sekitar?",
  "6.5.3": "Apakah Universitas melakukan dukungan dalam konservasi air di kampus?",
  "6.5.4": "Apakah Universitas mengetahui darimana sumber air bersihnya dan melakukan pengolahan dengan teknologi berkelanjutan?",
  "6.5.5": "Apakah Universitas pernah bekerja sama dengan pemerintah daerah / pemerintah pusat dan lembaga internasional tentang perlindungan air?",
  "6.5.6": "Apakah Universitas mempromosikan kesadaran / bijak dalam menggunakan air di lingkungan kampus?",
  "6.5.7": "Apakah Universitas mempromosikan kesadaran / bijak dalam menggunakan air di masyarakat?",
  "7.2.1": "Apakah Universitas memiliki peraturan terkait pembangunan / renovasi yang mengikuti standar efisiensi energi?",
  "7.2.2": "Apakah Universitas memiliki rencana untuk upgrade gedung / bangunan existing menjadi gedung yang memiliki efisiensi energi lebih tinggi?",
  "7.2.3": "Apakah Universitas memiliki mekanisme / proses dalam manajemen karbon dan pengurangan emisi CO₂?",
  "7.2.4": "Apakah Universitas memiliki rencana terkait energi efisiensi untuk mengurangi rata-rata konsumsi energi?",
  "7.2.5": "Apakah Universitas melakukan kajian untuk mengidentifikasi area yang boros / kehilangan energi paling dominan?",
  "7.2.6": "Apakah Universitas memiliki kebijakan divestasi investasi dari industri dengan energi dengan emisi karbon tinggi?",
  "7.4.1": "Apakah Universitas memiliki program kepada masyarakat terkait pembelajaran pentingnya efisiensi energi dan penggunaan energi bersih?",
  "7.4.2": "Apakah Universitas melakukan pernyataan secara terbuka tentang 100% penggunaan energi terbarukan?",
  "7.4.3": "Apakah Universitas memberikan layanan kepada industri lokal dalam peningkatan energi efisiensi dan energi bersih?",
  "7.4.4": "Apakah Universitas memberikan dukungan kepada pemerintah dalam pengembangan energi bersih dan kebijakan teknologi energi-efisien?",
  "7.4.5": "Apakah Universitas menyediakan layanan / bantuan kepada start-up dalam pengembangan ekonomi / teknologi rendah karbon?",
  "8.2.1": "Apakah Universitas membayar semua staf setidaknya UMR atau indikator kemiskinan lokal?",
  "8.2.2": "Apakah Universitas mengakui serikat pekerja untuk semua, termasuk perempuan & staf internasional?",
  "8.2.3": "Apakah Universitas memiliki kebijakan untuk mencegah/menghentikan diskriminasi di tempat kerja?",
  "8.2.4": "Apakah Universitas memiliki komitmen kebijakan terkait kerja paksa, perbudakan modern, perdagangan manusia, dan pekerja anak?",
  "8.2.5": "Apakah Universitas memiliki kebijakan untuk menjamin hak yang setara bagi pekerja saat melakukan outsourcing?",
  "8.2.6": "Apakah Universitas memiliki kebijakan tentang kesetaraan skala gaji termasuk komitmen untuk pengukuran dan penghapusan kesenjangan gaji terkait gender?",
  "8.2.7": "Apakah Universitas mengukur/melacak skala gaji mencerminkan kesetaraan gender?",
  "8.2.8": "Apakah Universitas memiliki proses bagi karyawan untuk mengajukan banding atas hak-hak karyawan dan/atau gaji?",
  "8.2.9": "Apakah Universitas mengakui hak-hak buruh (kebebasan berserikat & perundingan kolektif)?",
  "10.6.1": "Apakah Universitas memiliki kebijakan penerimaan yang tidak diskriminatif?",
  "10.6.2": "Apakah Universitas mengukur/melacak pendaftar & penerimaan kelompok minoritas?",
  "10.6.3": "Apakah Universitas mengambil tindakan terencana untuk merekrut mahasiswa/staf/dosen dari kelompok minoritas / kurang terwakili?",
  "10.6.4": "Apakah Universitas memiliki kebijakan anti-diskriminasi?",
  "10.6.5": "Apakah Universitas memiliki komite, kantor, dan/atau petugas terkait keberagaman dan kesetaraan?",
  "10.6.6": "Apakah Universitas menyediakan program bimbingan/konseling/dukungan sebaya untuk mendukung kelompok minoritas?",
  "10.6.7": "Apakah Universitas menyediakan fasilitas yang dapat diakses oleh penyandang disabilitas?",
  "10.6.8": "Apakah Universitas menyediakan layanan dukungan bagi penyandang disabilitas?",
  "10.6.9": "Apakah Universitas menyediakan skema akses bagi penyandang disabilitas?",
  "10.6.10": "Apakah Universitas Anda sebagai suatu badan memiliki kebijakan/strategi akomodasi yang wajar untuk penyandang disabilitas?",
  "10.6.11": "Apakah Universitas sebagai suatu badan memiliki kebijakan anti pelecehan?",
  "11.2.1": "Apakah Universitas menyediakan akses publik ke bangunan, monumen, atau lanskap warisan alam/budaya yang signifikan?",
  "11.2.2": "Apakah Universitas menyediakan akses publik ke perpustakaan termasuk buku dan publikasi?",
  "11.2.3": "Apakah Universitas menyediakan akses publik ke museum, ruang pameran/galeri, atau karya seni dan artefak?",
  "11.2.4": "Apakah Universitas menyediakan akses publik gratis ke ruang terbuka dan ruang hijau?",
  "11.2.5": "Apakah Universitas berkontribusi pada seni lokal melalui pertunjukan publik tahunan?",
  "11.2.6": "Apakah Universitas memberikan proyek untuk merekam dan/atau melestarikan warisan budaya tak benda?",
  "11.4.1": "Apakah Universitas mengukur dan menetapkan target untuk perjalanan yang lebih berkelanjutan?",
  "11.4.2": "Apakah Universitas melakukan tindakan untuk mempromosikan perjalanan yang lebih berkelanjutan?",
  "11.4.3": "Apakah Universitas mempromosikan atau mengizinkan kerja jarak jauh atau telecommuting?",
  "11.4.4": "Apakah Universitas menyediakan perumahan yang terjangkau bagi karyawan?",
  "11.4.5": "Apakah Universitas menyediakan perumahan yang terjangkau bagi mahasiswa?",
  "11.4.6": "Apakah Universitas memprioritaskan akses pejalan kaki di kampus?",
  "11.4.7": "Apakah Universitas bekerja sama dengan pemerintah daerah untuk mengatasi masalah perencanaan/pembangunan?",
  "11.4.8": "Apakah Universitas membangun gedung baru dengan standar yang berkelanjutan?",
  "11.4.9": "Apakah Universitas membangun di lokasi brownfield, jika memungkinkan?",
  "12.2.1": "Have a policy on ethical sourcing of food and supplies (apakah Universitas memiliki kebijakan pengadaan etis untuk makanan dan perlengkapan)?",
  "12.2.3": "Apakah Universitas memiliki kebijakan, proses, atau praktik tentang pembuangan limbah — termasuk limbah bahan berbahaya dan beracun (B3)?",
  "12.2.4": "Apakah Universitas memiliki kebijakan tentang pembuangan limbah untuk mengukur jumlah limbah?",
  "12.2.5": "Apakah Universitas memiliki kebijakan seputar minimisasi penggunaan plastik?",
  "12.2.6": "Apakah Universitas memiliki kebijakan seputar minimisasi penggunaan barang sekali pakai?",
  "12.2.7": "Apakah kebijakan ini berlaku untuk penyedia jasa?",
  "12.2.8": "Apakah kebijakan ini berlaku untuk penyedia barang?",
  "12.3.1": "Apakah Universitas mengukur jumlah limbah yang dihasilkan dan didaur ulang?",
  "12.4.1": "Apakah Universitas mempublikasikan Dokumen Sustainability Report tiap periode?",
  "13.2.1": "Apakah Universitas mengukur penggunaan jumlah energi berkarbon rendah?",
  "13.3.1": "Apakah Universitas melakukan edukasi / kampanye kepada masyarakat tentang resiko terjadinya perubahan iklim?",
  "13.3.2": "Apakah Universitas memiliki Climate Action Plan yang di sebarluaskan kepada masyarakat, pemerintah?",
  "13.3.3": "Apakah Universitas melakukan kerjasama di bidang bencana dan perubahan iklim?",
  "13.3.4": "Apakah Universitas memberikan dukungan dan informasi kepada pemerintah daerah, provinsi dalam bidang bencana perubahan iklim?",
  "13.3.5": "Apakah Universitas memiliki kolaborasi dengan LSM terkait adaptasi perubahan iklim?",
  "13.4.1": "Apakah Universitas memiliki target waktu (tanggal) mencapai Karbon Netral berdasarkan Protokol Greenhouse Gas?",
  "13.4.2": "Komitmen Karbon netral ditargetkan dicapai pada tanggal?",
  "14.2.1": "Apakah Universitas memberikan program pendidikan terkait bidang ekosistem air tawar untuk masyarakat lokal dan nasional?",
  "14.2.2": "Apakah Universitas menawarkan program pendidikan bagi masyarakat lokal atau nasional tentang pengelolaan perikanan?",
  "14.2.3": "Apakah Universitas menawarkan kegiatan pendidikan bagi masyarakat lokal untuk meningkatkan kesadaran tentang penangkapan ikan yang berlebihan?",
  "14.3.1": "Apakah Universitas mendukung dan/atau menyelenggarakan acara untuk mempromosikan konservasi laut?",
  "14.3.2": "Apakah Universitas memiliki kebijakan untuk memastikan bahwa makanan di kampus dari ekosistem perairan dipanen secara berkelanjutan?",
  "14.3.3": "Apakah Universitas bekerja secara langsung untuk memelihara dan memperluas ekosistem perairan?",
  "14.3.4": "Apakah Universitas bekerja secara langsung pada teknologi pencegahan kerusakan ekosistem air?",
  "14.4.1": "Apakah Universitas memiliki standar dan pedoman kualitas air untuk pembuangan air?",
  "14.4.2": "Apakah Universitas memiliki rencana aksi untuk mengurangi sampah plastik di kampus?",
  "14.4.3": "Apakah Universitas memiliki kebijakan untuk mencegah dan mengurangi segala jenis polusi laut?",
  "14.5.1": "Apakah Universitas memiliki rencana untuk meminimalkan perubahan pada ekosistem perairan terkait?",
  "14.5.2": "Apakah Universitas memantau kesehatan ekosistem perairan?",
  "14.5.3": "Apakah Universitas mengembangkan dan mendukung program stewardship ekosistem air?",
  "14.5.4": "Apakah Universitas berkolaborasi dengan masyarakat setempat dalam upaya menjaga ekosistem perairan?",
  "14.5.5": "Apakah Universitas telah menerapkan strategi pengelolaan daerah aliran sungai?",
  "15.2.1": "Apakah Universitas mendukung dan/atau menyelenggarakan acara untuk mempromosikan konservasi dan pemanfaatan lahan berkelanjutan?",
  "15.2.2": "Apakah Universitas memiliki kebijakan untuk memastikan bahwa makanan di kampus ditanam secara berkelanjutan?",
  "15.2.3": "Apakah Universitas bekerja secara langsung untuk memelihara dan memperluas ekosistem daratan?",
  "15.2.4": "Apakah Universitas menawarkan program pendidikan tentang ekosistem untuk masyarakat lokal atau nasional?",
  "15.2.5": "Apakah Universitas menawarkan program pendidikan/penjangkauan tentang pengelolaan lahan berkelanjutan untuk pertanian?",
  "15.2.6": "Apakah Universitas menawarkan program pendidikan/penjangkauan tentang pengelolaan lahan berkelanjutan untuk pariwisata?",
  "15.3.1": "Apakah Universitas memiliki kebijakan untuk konservasi, restorasi dan pemanfaatan berkelanjutan ekosistem darat?",
  "15.3.2": "Apakah Universitas memiliki kebijakan untuk melindungi spesies yang masuk daftar merah IUCN?",
  "15.3.3": "Apakah Universitas memasukkan keanekaragaman hayati lokal ke dalam setiap proses perencanaan dan pengembangan?",
  "15.3.4": "Apakah Universitas memiliki kebijakan untuk mengurangi dampak spesies asing di Kampus?",
  "15.3.5": "Apakah Universitas berkolaborasi dengan masyarakat setempat dalam upaya menjaga ekosistem lahan bersama?",
  "15.4.1": "Apakah Universitas memiliki standar dan pedoman kualitas air untuk pembuangan air (darat)?",
  "15.4.2": "Apakah Universitas memiliki kebijakan untuk mengurangi sampah plastik di kampus (darat)?",
  "15.4.3": "Apakah Universitas memiliki kebijakan, proses, atau praktik pembuangan limbah berbahaya dan beracun (B3) yang berdampak pada lahan?",
  "16.2.1": "Apakah Universitas memiliki perwakilan terpilih pada badan pengelola dari mahasiswa dan staff?",
  "16.2.2": "Apakah Universitas mengakui organisasi mahasiswa independen?",
  "16.2.3": "Apakah Universitas memiliki kebijakan dan prosedur tertulis untuk mengidentifikasi pemangku kepentingan lokal?",
  "16.2.4": "Apakah Universitas memastikan bahwa pemangku kepentingan lokal memiliki mekanisme untuk berpartisipasi dalam pengambilan keputusan universitas?",
  "16.2.5": "Apakah Universitas memiliki publikasi tentang prinsip dan komitmen terhadap kejahatan terorganisir, korupsi & penyuapan?",
  "16.2.6": "Apakah Universitas memiliki kebijakan untuk mendukung kebebasan akademis?",
  "16.2.7": "Apakah Universitas memiliki publikasi data keuangan Universitas?",
  "16.3.1": "Apakah Universitas memberikan saran ahli khusus kepada pemerintah lokal, regional, atau nasional?",
  "16.3.2": "Apakah Universitas menyediakan penjangkauan, pendidikan umum untuk para pembuat kebijakan?",
  "16.3.3": "Apakah Universitas melakukan penelitian yang berfokus pada kebijakan bekerja sama dengan departemen pemerintah?",
  "16.3.4": "Apakah Universitas menyediakan platform netral dan ruang \"aman\" bagi berbagai pemangku kepentingan politik?",
  "17.2.1": "Apakah Universitas memiliki keterlibatan langsung dalam pengembangan kebijakan SDGs pemerintah / NGO regional?",
  "17.2.2": "Apakah Universitas memulai dan berpartisipasi dalam dialog lintas sektor tentang SDGs?",
  "17.2.3": "Apakah Universitas berpartisipasi dalam kolaborasi internasional untuk mengumpulkan dan mengukur data SDGs?",
  "17.2.4": "Apakah Universitas mengembangkan praktik terbaik internasional dalam menangani SDGs?",
  "17.2.5": "Apakah Universitas berkolaborasi dengan NGO dalam menangani SDGs?",
  "17.4.1": "Apakah Universitas memiliki komitmen untuk memberikan pendidikan SDGs yang bermakna di seluruh universitas?",
  "17.4.2": "Apakah Universitas memiliki mata kuliah/program khusus yang membahas keberlanjutan dan SDGs?",
  "17.4.3": "Apakah Universitas memiliki kegiatan edukasi SDGs untuk komunitas yang lebih luas?",
  "17.4.4": "Apakah Universitas mengukur sustainability literacy mahasiswa?",
};
for (let i = 1; i <= 17; i++) {
  QUAL_QUESTIONS[`17.3.${i}`] = `Apakah Universitas mempublikasikan laporan progress terhadap SDG ${i} (sebagai laporan tersendiri atau bagian dari laporan tahunan)?`;
}

export const THE_SDG_CONFIG_2026: Record<number, SdgConfig> = {
  1: { number: 1, title: "No Poverty", emoji: "🏚️", color: "#E5243B", mandatory: true, indicators: [
    { code: "1.1.1", label: "Jumlah proporsi publikasi ilmiah terkait bersama", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "1.1.2", label: "Jumlah publikasi Sub topik kemiskinan / poverty", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "1.1.3", label: "Jumlah publikasi Sub topik kemiskinan / poverty", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "1.2.1", label: "Proporsi mahasiswa penerima bantuan keuangan untuk kuliah karena kemiskinan", type: "QUANTITATIVE", weightInSdg: 27, metrics: [{ key: "totalStudentsFTE", label: "1.2.1 Jumlah mahasiswa di Universitas", unit: "orang" }, { key: "lowIncomeStudentsWithAid", label: "1.2.2 Jumlah mahasiswa (S1/S2/S3) dari keluarga berpenghasilan rendah yang menerima bantuan keuangan", unit: "orang" }] },
    { code: "1.3.1", label: "Target penerimaan mahasiswa kelompok pendapatan rumah tangga 20% terbawah", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.3.2", label: "Target kelulusan/penyelesaian studi mahasiswa kelompok pendapatan 20% terbawah", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.3.3", label: "Dukungan (makanan, perumahan, transportasi, layanan hukum) untuk mahasiswa keluarga berpenghasilan rendah", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.3.4", label: "Program/inisiatif membantu mahasiswa kelompok pendapatan 20% terbawah menyelesaikan studi", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.3.5", label: "Skema dukungan mahasiswa ekonomi lemah dari negara berpenghasilan rendah/menengah ke bawah", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.4.1", label: "Bantuan komunitas lokal untuk memulai bisnis berkelanjutan via pendidikan/sumber daya", type: "QUALITATIVE", weightInSdg: 5.75, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.4.2", label: "Bantuan keuangan komunitas lokal untuk memulai bisnis berkelanjutan", type: "QUALITATIVE", weightInSdg: 5.75, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.4.3", label: "Pelatihan/program meningkatkan akses ke layanan dasar untuk semua", type: "QUALITATIVE", weightInSdg: 5.75, maxScore: 3, subQuestions: STD_3PT },
    { code: "1.4.4", label: "Partisipasi pembuatan kebijakan pengentasan kemiskinan (lokal/regional/nasional/global)", type: "QUALITATIVE", weightInSdg: 5.75, maxScore: 3, subQuestions: STD_3PT },
  ]},
  2: { number: 2, title: "Zero Hunger", emoji: "🌾", color: "#DDA63A", mandatory: false, indicators: [
    { code: "2.1.1", label: "Publikasi ilmiah terkait topik kelaparan", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "2.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "2.1.3", label: "Jumlah publikasi terkait topik kelaparan", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "2.2.1", label: "Sampah Makanan di Kampus", type: "QUALITATIVE", weightInSdg: 7.7, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.2.2", label: "Volume sampah makanan kampus per populasi", type: "QUANTITATIVE", weightInSdg: 7.7, metrics: [{ key: "totalFoodWasteTon", label: "2.2.2 Total sampah makanan", unit: "ton" }, { key: "campusPopulationFTE", label: "2.2.3 Total populasi di Universitas", unit: "orang" }] },
    { code: "2.3.1", label: "Program kerawanan pangan/kelaparan mahasiswa", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.3.2", label: "Intervensi mencegah/mengurangi kelaparan mahasiswa (gudang makanan)", type: "QUALITATIVE", weightInSdg: 2.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.3.3", label: "Pilihan makanan berkelanjutan untuk semua di kampus (vegetarian, vegan)", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.3.4", label: "Pilihan makanan sehat dan terjangkau untuk semua di kampus", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.3.5", label: "Intervensi mencegah/mengurangi kelaparan staf (lumbung pangan, uang makan)", type: "QUALITATIVE", weightInSdg: 2.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.4.1", label: "Proporsi lulusan bidang pertanian dan akuakultur termasuk aspek keberlanjutan", type: "QUANTITATIVE", weightInSdg: 19.2, metrics: [{ key: "totalGraduates", label: "2.4.1 Jumlah lulusan", unit: "orang" }, { key: "agricultureSustainGraduates", label: "2.4.2 Jumlah lulusan dari program studi bidang pertanian dan akuakultur", unit: "orang" }] },
    { code: "2.5.1", label: "Akses keamanan pangan & pengetahuan/teknologi pertanian/akuakultur berkelanjutan bagi petani lokal", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.5.2", label: "Acara petani & produsen pangan lokal untuk saling terhubung & transfer pengetahuan", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.5.3", label: "Akses fasilitas (lab, teknologi, stok tanaman) bagi petani/produsen pangan lokal", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "2.5.4", label: "Prioritas pembelian produk dari sumber lokal yang berkelanjutan", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 3, subQuestions: STD_3PT },
  ]},
  3: { number: 3, title: "Good Health and Well-being", emoji: "❤️", color: "#4C9F38", mandatory: true, indicators: [
    { code: "3.1.1", label: "Publikasi ilmiah terkait topik kesehatan pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "3.1.2", label: "Jumlah sitasi artikel pada panduan klinis / clinical guidance", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "3.1.3", label: "Jumlah publikasi terkait topik kesehatan (total)", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "3.2.1", label: "Jumlah mahasiswa yang lulus dalam profesi kesehatan", type: "QUANTITATIVE", weightInSdg: 34.6, metrics: [{ key: "totalGraduates", label: "3.2.1 Jumlah lulusan", unit: "orang" }, { key: "healthProfGraduates", label: "3.2.2 Jumlah lulusan dalam profesi kesehatan", unit: "orang" }] },
    { code: "3.3.1", label: "Kolaborasi dengan lembaga kesehatan lokal/nasional/global", type: "QUALITATIVE", weightInSdg: 7, maxScore: 3, subQuestions: STD_3PT },
    { code: "3.3.2", label: "Program & proyek penjangkauan kesehatan & kesejahteraan komunitas", type: "QUALITATIVE", weightInSdg: 7, maxScore: 3, subQuestions: STD_3PT },
    { code: "3.3.3", label: "Berbagi fasilitas olahraga dengan komunitas lokal", type: "QUALITATIVE", weightInSdg: 2.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "3.3.4", label: "Akses layanan kesehatan seksual & reproduksi mahasiswa", type: "QUALITATIVE", weightInSdg: 7, maxScore: 3, subQuestions: STD_3PT },
    { code: "3.3.5", label: "Akses dukungan kesehatan mental mahasiswa", type: "QUALITATIVE", weightInSdg: 3.5, maxScore: 3, subQuestions: STD_3PT },
    { code: "3.3.6", label: "Kebijakan bebas asap rokok", type: "QUALITATIVE", weightInSdg: 8, maxScore: 4, subQuestions: STD_4PT },
    { code: "3.3.7", label: "Akses dukungan kesehatan mental pegawai/staf", type: "QUALITATIVE", weightInSdg: 3.5, maxScore: 3, subQuestions: STD_3PT },
  ]},
  4: { number: 4, title: "Quality Education", emoji: "🎓", color: "#C5192D", mandatory: true, indicators: [
    { code: "4.1.1", label: "Jumlah artikel yang dilihat dan di download", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "4.1.2", label: "Publikasi ilmiah pada top 10% Jurnal berdasarkan citescore matrix", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "4.1.3", label: "Jumlah publikasi total", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "4.2.1", label: "Proporsi lulusan dengan kualifikasi untuk mengajar", type: "QUANTITATIVE", weightInSdg: 15.4, metrics: [{ key: "totalGraduates", label: "4.2.1 Jumlah lulusan", unit: "orang" }, { key: "primaryTeachingGraduates", label: "4.2.2 Jumlah lulusan yang memperoleh kualifikasi untuk mengajar di tingkat sekolah dasar", unit: "orang" }] },
    { code: "4.3.1", label: "Akses gratis sumber daya pendidikan untuk non-mahasiswa", type: "QUALITATIVE", weightInSdg: 5, maxScore: 3, subQuestions: STD_3PT },
    { code: "4.3.2", label: "Acara universitas terbuka untuk masyarakat umum (kuliah umum)", type: "QUALITATIVE", weightInSdg: 5, maxScore: 3, subQuestions: STD_3PT },
    { code: "4.3.3", label: "Program pendidikan khusus/pelatihan kejuruan untuk non-mahasiswa", type: "QUALITATIVE", weightInSdg: 5, maxScore: 3, subQuestions: STD_3PT },
    { code: "4.3.4", label: "Kegiatan pendidikan di luar kampus (sekolah lokal, masyarakat)", type: "QUALITATIVE", weightInSdg: 5, maxScore: 3, subQuestions: STD_3PT },
    { code: "4.3.5", label: "Kebijakan akses tanpa diskriminasi", type: "QUALITATIVE", weightInSdg: 6.8, maxScore: 4, subQuestions: STD_4PT },
    { code: "4.3.6", label: "Peraturan dibuat pada tahun?", type: "QUANTITATIVE", weightInSdg: 0, metrics: [{ key: "policyCreatedYear", label: "4.3.6 Peraturan dibuat pada tahun?", unit: "tahun" }] },
    { code: "4.3.7", label: "Peraturan direview pada tahun?", type: "QUANTITATIVE", weightInSdg: 0, metrics: [{ key: "policyReviewedYear", label: "4.3.7 Peraturan direview pada tahun?", unit: "tahun" }] },
    { code: "4.4.1", label: "Proporsi mahasiswa generasi pertama", type: "QUANTITATIVE", weightInSdg: 30.8, metrics: [{ key: "totalStudents", label: "4.4.1 Jumlah mahasiswa", unit: "orang" }, { key: "studentsStartingDegree", label: "4.4.2 Jumlah mahasiswa yang memulai kuliah", unit: "orang" }, { key: "firstGenStudents", label: "4.4.3 Jumlah mahasiswa generasi pertama yang memulai kuliah", unit: "orang" }] },
  ]},
  5: { number: 5, title: "Gender Equality", emoji: "⚧️", color: "#FF3A21", mandatory: false, indicators: [
    { code: "5.1.1", label: "Proporsi peneliti wanita pada penelitian", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "5.1.2", label: "Publikasi ilmiah oleh peneliti wanita pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "5.1.3", label: "Jumlah publikasi terkait topik kesetaraan gender", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "5.2.1", label: "Proporsi mahasiswa perempuan generasi/anak pertama", type: "QUANTITATIVE", weightInSdg: 15.4, metrics: [{ key: "totalStudentsFTE", label: "5.2.1 Jumlah mahasiswa di Universitas", unit: "orang" }, { key: "studentsStartingDegree", label: "5.2.2 Jumlah mahasiswa yang baru memulai kuliah", unit: "orang" }, { key: "firstGenStudentsStarting", label: "5.2.3 Jumlah mahasiswa generasi/anak pertama yang baru memulai kuliah", unit: "orang" }, { key: "femaleStudentsStarting", label: "5.2.4 Jumlah mahasiswa perempuan yang baru memulai", unit: "orang" }, { key: "firstGenFemaleStudents", label: "5.2.5 Jumlah mahasiswa perempuan generasi/anak pertama", unit: "orang" }] },
    { code: "5.3.1", label: "Pelacakan tingkat penerimaan & kelulusan perempuan", type: "QUALITATIVE", weightInSdg: 1.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "5.3.2", label: "Kebijakan penerimaan & partisipasi perempuan", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 4, subQuestions: STD_4PT },
    { code: "5.3.3", label: "Skema akses perempuan (mentoring, beasiswa)", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "5.3.4", label: "Mendorong pendaftaran perempuan di bidang underrepresented", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "5.4.1", label: "Proporsi akademisi senior perempuan", type: "QUANTITATIVE", weightInSdg: 15.4, metrics: [{ key: "totalEmployeesFTE", label: "5.4.1 Jumlah pegawai", unit: "orang" }, { key: "totalAcademicFTE", label: "5.4.2 Jumlah staf akademik", unit: "orang" }, { key: "totalSeniorAcademicFTE", label: "5.4.3 Jumlah staf akademik senior", unit: "orang" }, { key: "femaleSeniorAcademicFTE", label: "5.4.4 Jumlah staf akademik senior perempuan", unit: "orang" }] },
    { code: "5.5.1", label: "Proporsi perempuan yang menerima gelar", type: "QUANTITATIVE", weightInSdg: 11.5, metrics: [{ key: "totalGraduates", label: "5.5.1 Jumlah lulusan", unit: "orang" }, { key: "graduatesSTEM", label: "5.5.2 Jumlah lulusan STEM", unit: "orang" }, { key: "graduatesMedicine", label: "5.5.3 Jumlah lulusan Kedokteran", unit: "orang" }, { key: "graduatesArts", label: "5.5.4 Jumlah lulusan Seni & Humaniora/Ilmu Sosial", unit: "orang" }, { key: "femaleGraduatesSTEM", label: "5.5.5 Jumlah lulusan perempuan STEM", unit: "orang" }, { key: "femaleGraduatesMedicine", label: "5.5.6 Jumlah lulusan perempuan Kedokteran", unit: "orang" }, { key: "femaleGraduatesArts", label: "5.5.7 Jumlah lulusan perempuan Seni & Humaniora", unit: "orang" }] },
    { code: "5.6.1", label: "Kebijakan non-diskriminasi terhadap perempuan", type: "QUALITATIVE", weightInSdg: 1.95, maxScore: 4, subQuestions: STD_4PT },
    { code: "5.6.2", label: "Kebijakan non-diskriminasi transgender", type: "QUALITATIVE", weightInSdg: 1.95, maxScore: 4, subQuestions: STD_4PT },
    { code: "5.6.3", label: "Kebijakan cuti melahirkan", type: "QUALITATIVE", weightInSdg: 0.95, maxScore: 4, subQuestions: STD_4PT },
    { code: "5.6.4", label: "Fasilitas childcare untuk mahasiswa", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "5.6.5", label: "Fasilitas childcare untuk staf", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "5.6.6", label: "Skema mentoring perempuan (>=10% mahasiswi)", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "5.6.7", label: "Pelacakan tingkat kelulusan perempuan", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "5.6.8", label: "Kebijakan perlindungan pelapor diskriminasi", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 4, subQuestions: STD_4PT },
    { code: "5.6.9", label: "Kebijakan cuti ayah", type: "QUALITATIVE", weightInSdg: 0.95, maxScore: 4, subQuestions: STD_4PT },
  ]},
  6: { number: 6, title: "Clean Water and Sanitation", emoji: "💧", color: "#26BDE2", mandatory: false, indicators: [
    { code: "6.1.1", label: "Publikasi ilmiah terkait topik air dan sanitasi pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "6.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "6.1.3", label: "Jumlah publikasi terkait topik air dan sanitasi", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "6.2.1", label: "Pengukuran sumber air yang digunakan", type: "QUALITATIVE", weightInSdg: 9.5, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.2.2", label: "Volume konsumsi air per populasi", type: "QUANTITATIVE", weightInSdg: 9.5, metrics: [{ key: "waterUsedM3", label: "6.2.2 Berapa volume air yang digunakan tiap bulan?", unit: "m³" }, { key: "campusPopulationFTE", label: "6.2.2 Berapa jumlah populasi Universitas?", unit: "orang" }] },
    { code: "6.3.1", label: "Proses pengolahan air limbah", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.3.2", label: "Pencegahan polusi sistem air", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.3.3", label: "Air minum gratis disediakan", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.3.4", label: "Standar bangunan hemat air", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.3.5", label: "Penanaman tanaman hemat air", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.4.1", label: "Kebijakan daur ulang air", type: "QUALITATIVE", weightInSdg: 6, maxScore: 4, subQuestions: STD_4PT },
    { code: "6.4.2", label: "Pengukuran daur ulang air", type: "QUALITATIVE", weightInSdg: 6, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.5.1", label: "Kesempatan belajar manajemen air untuk komunitas", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.5.3", label: "Dukungan konservasi air di luar kampus", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.5.4", label: "Teknologi ekstraksi air berkelanjutan", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.5.5", label: "Kerjasama keamanan air dengan pemerintah", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.5.6", label: "Promosi penggunaan air bijak di kampus", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "6.5.7", label: "Promosi penggunaan air bijak di komunitas", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
  ]},
  7: { number: 7, title: "Affordable and Clean Energy", emoji: "⚡", color: "#FCC30B", mandatory: false, indicators: [
    { code: "7.1.1", label: "Publikasi ilmiah terkait topik energi pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "7.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "7.1.3", label: "Jumlah publikasi terkait topik energi dan energi efisien", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "7.2.1", label: "Kebijakan renovasi/bangunan baru hemat energi", type: "QUALITATIVE", weightInSdg: 3.85, maxScore: 4, subQuestions: STD_4PT },
    { code: "7.2.2", label: "Rencana upgrade efisiensi energi bangunan lama", type: "QUALITATIVE", weightInSdg: 3.85, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.2.3", label: "Proses pengurangan emisi karbon", type: "QUALITATIVE", weightInSdg: 3.85, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.2.4", label: "Rencana pengurangan konsumsi energi", type: "QUALITATIVE", weightInSdg: 3.85, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.2.5", label: "Review identifikasi pemborosan energi", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.2.6", label: "Kebijakan divestasi dari industri energi karbon intensif", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 4, subQuestions: STD_4PT },
    { code: "7.3.1", label: "Densitas penggunaan energi (energi per m2 lantai)", type: "QUANTITATIVE", weightInSdg: 17, metrics: [{ key: "totalEnergyGJ", label: "7.3.1 Total energi yang digunakan", unit: "GJ" }, { key: "floorSpaceM2", label: "7.3.2 Luas Lantai di Universitas", unit: "m²" }] },
    { code: "7.4.1", label: "Outreach efisiensi energi untuk komunitas lokal", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.4.2", label: "Promosi pledge 100% energi terbarukan", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.4.3", label: "Layanan efisiensi energi untuk industri lokal", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.4.4", label: "Dukungan kebijakan energi bersih untuk pemerintah", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.4.5", label: "Bantuan startup inovasi rendah karbon", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "7.5.1", label: "Penggunaan energi rendah karbon", type: "QUANTITATIVE", weightInSdg: 10, metrics: [{ key: "totalEnergyGJ", label: "7.5.1 Total energi yang digunakan", unit: "GJ" }, { key: "lowCarbonEnergyGJ", label: "7.5.2 Total energi dengan sumber energi rendah karbon", unit: "GJ" }] },
  ]},
  8: { number: 8, title: "Decent Work and Economic Growth", emoji: "💼", color: "#A21942", mandatory: true, indicators: [
    { code: "8.1.1", label: "Publikasi ilmiah terkait topik ekonomi dan pekerjaan yang layak pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 14 },
    { code: "8.1.2", label: "Jumlah publikasi terkait topik ekonomi dan pekerjaan yang layak", type: "BIBLIOMETRIC", weightInSdg: 13 },
    { code: "8.2.1", label: "Gaji minimum living wage untuk semua staf", type: "QUALITATIVE", weightInSdg: 2.45, maxScore: 3, subQuestions: STD_3PT },
    { code: "8.2.2", label: "Pengakuan serikat buruh", type: "QUALITATIVE", weightInSdg: 1.22, maxScore: 3, subQuestions: STD_3PT },
    { code: "8.2.3", label: "Kebijakan anti-diskriminasi di tempat kerja", type: "QUALITATIVE", weightInSdg: 2.45, maxScore: 4, subQuestions: STD_4PT },
    { code: "8.2.4", label: "Kebijakan anti-perbudakan modern & perdagangan manusia", type: "QUALITATIVE", weightInSdg: 2.45, maxScore: 4, subQuestions: STD_4PT },
    { code: "8.2.5", label: "Kebijakan hak setara saat outsourcing", type: "QUALITATIVE", weightInSdg: 2.45, maxScore: 4, subQuestions: STD_4PT },
    { code: "8.2.6", label: "Kebijakan kesetaraan skala gaji (gender pay gap)", type: "QUALITATIVE", weightInSdg: 2.45, maxScore: 4, subQuestions: STD_4PT },
    { code: "8.2.7", label: "Pelacakan kesetaraan skala gaji gender", type: "QUALITATIVE", weightInSdg: 2.45, maxScore: 3, subQuestions: STD_3PT },
    { code: "8.2.8", label: "Proses banding hak karyawan", type: "QUALITATIVE", weightInSdg: 2.45, maxScore: 3, subQuestions: STD_3PT },
    { code: "8.2.9", label: "Pengakuan hak-hak buruh (kebebasan berserikat)", type: "QUALITATIVE", weightInSdg: 1.22, maxScore: 3, subQuestions: STD_3PT },
    { code: "8.3.1", label: "Pengeluaran per pegawai", type: "QUANTITATIVE", weightInSdg: 15.4, metrics: [{ key: "totalEmployeesFTE", label: "8.3.1 Jumlah pegawai", unit: "orang" }, { key: "totalAcademicFTE", label: "8.3.2 Jumlah staf akademik", unit: "orang" }, { key: "universityExpenditureLocal", label: "8.3.3 Pengeluaran Universitas", unit: "IDR" }] },
    { code: "8.4.1", label: "Proporsi mahasiswa yang mengikuti magang lebih dari satu bulan", type: "QUANTITATIVE", weightInSdg: 19, metrics: [{ key: "totalStudentsFTE", label: "8.4.1 Jumlah mahasiswa di Universitas", unit: "orang" }, { key: "studentsWithPlacementFTE", label: "8.4.2 Jumlah mahasiswa yang magang lebih dari satu bulan", unit: "orang" }] },
    { code: "8.5.1", label: "Proporsi pegawai dengan kontrak tetap", type: "QUANTITATIVE", weightInSdg: 19, metrics: [{ key: "totalEmployeesFTE", label: "8.5.1 Jumlah pegawai", unit: "orang" }, { key: "secureContractEmployeesFTE", label: "8.5.2 Jumlah karyawan dengan kontrak lebih dari 24 bulan", unit: "orang" }] },
  ]},
  9: { number: 9, title: "Industry, Innovation and Infrastructure", emoji: "🏭", color: "#FD6925", mandatory: false, indicators: [
    { code: "9.1.1", label: "Jumlah publikasi terkait industri, inovasi, dan infrastruktur", type: "BIBLIOMETRIC", weightInSdg: 11.6 },
    { code: "9.2.1", label: "Jumlah paten yang disitasi dalam penelitian atau paten di masyarakat dan industri", type: "BIBLIOMETRIC", weightInSdg: 15.4 },
    { code: "9.3.1", label: "Jumlah University spin-off / perusahaan yang dihasilkan berdasarkan penelitian", type: "QUANTITATIVE", weightInSdg: 34.6, metrics: [{ key: "activeSpinOffs", label: "9.3.1 Jumlah University spin-off / perusahaan aktif (>=3 tahun)", unit: "perusahaan" }] },
    { code: "9.4.1", label: "Pendapatan penelitian dari industri dan komersial per staf akademik", type: "QUANTITATIVE", weightInSdg: 38.4, metrics: [{ key: "researchIncomeSTEM", label: "9.4.1 Pendapatan penelitian industri & komersial STEM", unit: "IDR" }, { key: "researchIncomeMedicine", label: "9.4.1 Pendapatan penelitian industri & komersial Medicine", unit: "IDR" }, { key: "researchIncomeArts", label: "9.4.1 Pendapatan penelitian industri & komersial Arts/Humaniora", unit: "IDR" }, { key: "academicStaffSTEM", label: "9.4.2 Staf akademik STEM", unit: "orang" }, { key: "academicStaffMedicine", label: "9.4.2 Staf akademik Medicine", unit: "orang" }, { key: "academicStaffArts", label: "9.4.2 Staf akademik Arts/Humaniora", unit: "orang" }] },
  ]},
  10: { number: 10, title: "Reduced Inequalities", emoji: "⚖️", color: "#DD1367", mandatory: false, indicators: [
    { code: "10.1.1", label: "Publikasi ilmiah terkait topik penurunan inequality pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "10.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "10.1.3", label: "Jumlah publikasi terkait topik penurunan inequality", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "10.2.1", label: "Mahasiswa generasi/anak pertama", type: "QUANTITATIVE", weightInSdg: 15.5, metrics: [{ key: "totalStudentsFTE", label: "10.2.1 Jumlah mahasiswa di Universitas", unit: "orang" }, { key: "studentsStartingDegree", label: "10.2.1 Jumlah mahasiswa yang baru memulai kuliah", unit: "orang" }, { key: "firstGenStudents", label: "10.2.1 Jumlah mahasiswa generasi/anak pertama", unit: "orang" }] },
    { code: "10.3.1", label: "Mahasiswa internasional dari negara berkembang", type: "QUANTITATIVE", weightInSdg: 15.5, metrics: [{ key: "totalStudentsFTE", label: "10.3.1 Jumlah mahasiswa di Universitas", unit: "orang" }, { key: "intlStudentsDevelopingCountries", label: "10.3.1 Jumlah mahasiswa internasional dari negara berkembang", unit: "orang" }] },
    { code: "10.4.1", label: "Proporsi mahasiswa penyandang disabilitas", type: "QUANTITATIVE", weightInSdg: 11.5, metrics: [{ key: "totalStudentsFTE", label: "10.4.1 Jumlah mahasiswa di Universitas", unit: "orang" }, { key: "studentsWithDisabilityFTE", label: "10.4.1 Jumlah mahasiswa penyandang disabilitas", unit: "orang" }] },
    { code: "10.5.1", label: "Proporsi pegawai penyandang disabilitas", type: "QUANTITATIVE", weightInSdg: 11.5, metrics: [{ key: "totalEmployeesFTE", label: "10.5.1 Jumlah pegawai", unit: "orang" }, { key: "employeesWithDisabilityFTE", label: "10.5.1 Jumlah pegawai penyandang disabilitas", unit: "orang" }] },
    { code: "10.6.1", label: "Kebijakan penerimaan non-diskriminatif", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 4, subQuestions: STD_4PT },
    { code: "10.6.2", label: "Pelacakan pendaftaran kelompok underrepresented", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.3", label: "Tindakan rekrutmen kelompok underrepresented", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.4", label: "Kebijakan anti-diskriminasi", type: "QUALITATIVE", weightInSdg: 0.95, maxScore: 4, subQuestions: STD_4PT },
    { code: "10.6.5", label: "Petugas/komite keberagaman & kesetaraan", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.6", label: "Dukungan untuk kelompok underrepresented", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.7", label: "Fasilitas aksesibel untuk penyandang disabilitas", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.8", label: "Layanan pendukung penyandang disabilitas", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.9", label: "Skema akses penyandang disabilitas", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.10", label: "Kebijakan akomodasi wajar penyandang disabilitas", type: "QUALITATIVE", weightInSdg: 1.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "10.6.11", label: "Kebijakan anti-pelecehan", type: "QUALITATIVE", weightInSdg: 0.95, maxScore: 4, subQuestions: STD_4PT },
  ]},
  11: { number: 11, title: "Sustainable Cities and Communities", emoji: "🏙️", color: "#FD9D24", mandatory: false, indicators: [
    { code: "11.1.1", label: "Publikasi ilmiah terkait topik kota berkelanjutan pada top 10%", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "11.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "11.1.3", label: "Jumlah publikasi terkait topik kota berkelanjutan", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "11.2.1", label: "Akses publik ke gedung/monumen bersejarah", type: "QUALITATIVE", weightInSdg: 3.75, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.2.2", label: "Akses publik ke perpustakaan", type: "QUALITATIVE", weightInSdg: 3.75, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.2.3", label: "Akses publik ke museum/galeri/koleksi seni", type: "QUALITATIVE", weightInSdg: 3.75, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.2.4", label: "Akses publik ke ruang hijau/terbuka", type: "QUALITATIVE", weightInSdg: 3.75, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.2.5", label: "Kontribusi seni & pertunjukan publik", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.2.6", label: "Proyek pelestarian warisan budaya tak benda", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.3.1", label: "Pengeluaran untuk seni & warisan budaya", type: "QUANTITATIVE", weightInSdg: 15.3, metrics: [{ key: "totalUniversityExpenditure", label: "Total pengeluaran universitas (IDR)", unit: "IDR" }, { key: "artsHeritageExpenditure", label: "Pengeluaran untuk seni & warisan (IDR)", unit: "IDR" }] },
    { code: "11.4.1", label: "Pengukuran & target komuter berkelanjutan", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.2", label: "Promosi komuter berkelanjutan", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.3", label: "Kebijakan kerja remote/telecommuting", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.4", label: "Perumahan terjangkau untuk karyawan", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.5", label: "Perumahan terjangkau untuk mahasiswa", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.6", label: "Prioritas pejalan kaki di kampus", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.7", label: "Kolaborasi dengan pemda soal perencanaan & pengembangan", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.8", label: "Standar pembangunan berkelanjutan untuk gedung baru", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
    { code: "11.4.9", label: "Pembangunan di lahan brownfield", type: "QUALITATIVE", weightInSdg: 3.9, maxScore: 3, subQuestions: STD_3PT },
  ]},
  12: { number: 12, title: "Responsible Consumption and Production", emoji: "♻️", color: "#BF8B2E", mandatory: false, indicators: [
    { code: "12.1.1", label: "Publikasi ilmiah terkait topik produksi dan konsumsi yang bertanggung jawab pada top 10%", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "12.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "12.1.3", label: "Jumlah publikasi terkait topik produksi dan konsumsi yang bertanggung jawab", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "12.2.1", label: "Kebijakan pengadaan etis makanan dan perlengkapan", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 4, subQuestions: STD_4PT },
    { code: "12.2.3", label: "Kebijakan pembuangan limbah bahan berbahaya", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 4, subQuestions: STD_4PT },
    { code: "12.2.4", label: "Kebijakan pengurangan limbah ke TPA", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 4, subQuestions: STD_4PT },
    { code: "12.2.5", label: "Kebijakan minimalisasi penggunaan plastik", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 4, subQuestions: STD_4PT },
    { code: "12.2.6", label: "Kebijakan minimalisasi barang sekali pakai", type: "QUALITATIVE", weightInSdg: 4.8, maxScore: 4, subQuestions: STD_4PT },
    { code: "12.2.7", label: "Kebijakan minimalisasi diperluas ke outsourced services", type: "QUALITATIVE", weightInSdg: 1.35, maxScore: 3, subQuestions: STD_3PT },
    { code: "12.2.8", label: "Kebijakan minimalisasi diperluas ke pemasok", type: "QUALITATIVE", weightInSdg: 1.35, maxScore: 3, subQuestions: STD_3PT },
    { code: "12.3.1", label: "Pelacakan limbah dan daur ulang kampus", type: "QUALITATIVE", weightInSdg: 13.5, maxScore: 3, subQuestions: STD_3PT },
    { code: "12.3.2", label: "Proporsi limbah yang didaur ulang", type: "QUANTITATIVE", weightInSdg: 13.5, metrics: [{ key: "totalWasteTon", label: "12.3.2 Jumlah limbah yang dihasilkan", unit: "ton" }, { key: "recycledWasteTon", label: "12.3.2 Jumlah limbah yang didaur ulang", unit: "ton" }, { key: "landfillWasteTon", label: "12.3.2 Jumlah limbah yang dikirim ke TPA", unit: "ton" }] },
    { code: "12.4.1", label: "Publikasi laporan keberlanjutan universitas", type: "QUALITATIVE", weightInSdg: 19.3, maxScore: 3, subQuestions: STD_3PT },
  ]},
  13: { number: 13, title: "Climate Action", emoji: "🌍", color: "#3F7E44", mandatory: false, indicators: [
    { code: "13.1.1", label: "Publikasi ilmiah terkait topik Climate Action pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "13.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "13.1.3", label: "Jumlah publikasi terkait Climate Action / Climate change", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "13.2.1", label: "Pelacakan penggunaan energi rendah karbon", type: "QUALITATIVE", weightInSdg: 13.5, maxScore: 3, subQuestions: STD_3PT },
    { code: "13.2.2", label: "Volume energi rendah karbon yang digunakan", type: "QUANTITATIVE", weightInSdg: 13.5, metrics: [{ key: "totalEnergyGJ", label: "13.2.2 Total energi yang digunakan", unit: "GJ" }, { key: "lowCarbonEnergyGJ", label: "13.2.3 Total energi dari sumber dengan karbon rendah", unit: "GJ" }] },
    { code: "13.3.1", label: "Program edukasi lokal tentang iklim", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "13.3.2", label: "Climate Action Plan dibagikan ke pemda & komunitas", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "13.3.3", label: "Perencanaan kooperatif bencana iklim", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "13.3.4", label: "Dukungan pemerintah lokal untuk early warning iklim", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "13.3.5", label: "Kolaborasi dengan NGO untuk adaptasi iklim", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "13.4.1", label: "Komitmen menuju universitas netral karbon", type: "QUALITATIVE", weightInSdg: 11.5, maxScore: 5, subQuestions: STD_4PT },
    { code: "13.4.2", label: "Target tanggal pencapaian netral karbon", type: "QUALITATIVE", weightInSdg: 11.5, maxScore: 4, subQuestions: STD_3PT },
  ]},
  14: { number: 14, title: "Life Below Water", emoji: "🌊", color: "#0A97D9", mandatory: false, indicators: [
    { code: "14.1.1", label: "Publikasi ilmiah terkait topik Life below water pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "14.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "14.1.3", label: "Jumlah publikasi terkait Life below water", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "14.2.1", label: "Program edukasi ekosistem air tawar untuk komunitas", type: "QUALITATIVE", weightInSdg: 5.1, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.2.2", label: "Program edukasi perikanan berkelanjutan", type: "QUALITATIVE", weightInSdg: 5.1, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.2.3", label: "Outreach tentang overfishing & penangkapan ikan ilegal", type: "QUALITATIVE", weightInSdg: 5.1, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.3.1", label: "Event promosi konservasi laut/sungai/danau", type: "QUALITATIVE", weightInSdg: 4.85, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.3.2", label: "Kebijakan makanan laut dipanen secara berkelanjutan", type: "QUALITATIVE", weightInSdg: 4.85, maxScore: 4, subQuestions: STD_4PT },
    { code: "14.3.3", label: "Kerja langsung menjaga biodiversitas ekosistem air", type: "QUALITATIVE", weightInSdg: 4.85, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.3.4", label: "Teknologi pencegahan kerusakan ekosistem air", type: "QUALITATIVE", weightInSdg: 4.85, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.4.1", label: "Standar kualitas air untuk pembuangan", type: "QUALITATIVE", weightInSdg: 6.45, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.4.2", label: "Rencana aksi pengurangan sampah plastik kampus", type: "QUALITATIVE", weightInSdg: 6.45, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.4.3", label: "Kebijakan pencegahan polusi laut", type: "QUALITATIVE", weightInSdg: 6.4, maxScore: 4, subQuestions: STD_4PT },
    { code: "14.5.1", label: "Rencana minimalisasi perubahan ekosistem air lokal", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.5.2", label: "Pemantauan kesehatan ekosistem air", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.5.3", label: "Program stewardship ekosistem air", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.5.4", label: "Kolaborasi komunitas menjaga ekosistem air bersama", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
    { code: "14.5.5", label: "Strategi pengelolaan daerah tangkapan air (watershed)", type: "QUALITATIVE", weightInSdg: 3.8, maxScore: 3, subQuestions: STD_3PT },
  ]},
  15: { number: 15, title: "Life On Land", emoji: "🌿", color: "#56C02B", mandatory: false, indicators: [
    { code: "15.1.1", label: "Publikasi ilmiah terkait topik Life on land pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "15.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "15.1.3", label: "Jumlah publikasi terkait Life on land", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "15.2.1", label: "Event penggunaan berkelanjutan lahan & hutan", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.2.2", label: "Kebijakan makanan di kampus dari pertanian berkelanjutan", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 4, subQuestions: STD_4PT },
    { code: "15.2.3", label: "Kerja langsung menjaga biodiversitas ekosistem darat", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.2.4", label: "Program edukasi ekosistem (flora & fauna) untuk komunitas", type: "QUALITATIVE", weightInSdg: 4.6, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.2.5", label: "Outreach pengelolaan lahan pertanian berkelanjutan", type: "QUALITATIVE", weightInSdg: 2.3, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.2.6", label: "Outreach pengelolaan lahan pariwisata berkelanjutan", type: "QUALITATIVE", weightInSdg: 2.3, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.3.1", label: "Kebijakan konservasi & penggunaan berkelanjutan lahan", type: "QUALITATIVE", weightInSdg: 5.4, maxScore: 4, subQuestions: STD_4PT },
    { code: "15.3.2", label: "Kebijakan perlindungan spesies IUCN Red List", type: "QUALITATIVE", weightInSdg: 5.4, maxScore: 4, subQuestions: STD_4PT },
    { code: "15.3.3", label: "Biodiversitas lokal dalam perencanaan & pembangunan", type: "QUALITATIVE", weightInSdg: 5.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.3.4", label: "Kebijakan pengurangan dampak spesies asing invasif", type: "QUALITATIVE", weightInSdg: 5.4, maxScore: 4, subQuestions: STD_4PT },
    { code: "15.3.5", label: "Kolaborasi komunitas menjaga ekosistem darat bersama", type: "QUALITATIVE", weightInSdg: 5.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.4.1", label: "Standar kualitas air pembuangan (land-sensitive)", type: "QUALITATIVE", weightInSdg: 7.7, maxScore: 3, subQuestions: STD_3PT },
    { code: "15.4.2", label: "Kebijakan pengurangan sampah plastik kampus (darat)", type: "QUALITATIVE", weightInSdg: 7.65, maxScore: 4, subQuestions: STD_4PT },
    { code: "15.4.3", label: "Kebijakan pembuangan limbah berbahaya (darat)", type: "QUALITATIVE", weightInSdg: 7.65, maxScore: 4, subQuestions: STD_4PT },
  ]},
  16: { number: 16, title: "Peace, Justice and Strong Institutions", emoji: "🏛️", color: "#00689D", mandatory: false, indicators: [
    { code: "16.1.1", label: "Publikasi ilmiah terkait topik Peace, Justice and Strong Institutions pada top 10% Jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "16.1.2", label: "Jumlah sitasi artikel pada top jurnal", type: "BIBLIOMETRIC", weightInSdg: 10 },
    { code: "16.1.3", label: "Jumlah publikasi terkait Peace, Justice and Strong Institutions", type: "BIBLIOMETRIC", weightInSdg: 7 },
    { code: "16.2.1", label: "Keterwakilan terpilih di badan pemerintahan universitas", type: "QUALITATIVE", weightInSdg: 3.35, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.2.2", label: "Pengakuan senat/organisasi mahasiswa independen", type: "QUALITATIVE", weightInSdg: 3.35, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.2.3", label: "Kebijakan keterlibatan pemangku kepentingan lokal", type: "QUALITATIVE", weightInSdg: 3.35, maxScore: 4, subQuestions: STD_4PT },
    { code: "16.2.4", label: "Badan partisipatif untuk stakeholder lokal", type: "QUALITATIVE", weightInSdg: 3.35, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.2.5", label: "Prinsip anti-korupsi & suap dipublikasikan", type: "QUALITATIVE", weightInSdg: 3.35, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.2.6", label: "Kebijakan kebebasan akademik", type: "QUALITATIVE", weightInSdg: 6.6, maxScore: 4, subQuestions: STD_4PT },
    { code: "16.2.7", label: "Publikasi data keuangan universitas", type: "QUALITATIVE", weightInSdg: 3.25, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.3.1", label: "Penyediaan saran ahli kepada pemerintah", type: "QUALITATIVE", weightInSdg: 6.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.3.2", label: "Outreach & pendidikan untuk pembuat kebijakan", type: "QUALITATIVE", weightInSdg: 6.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.3.3", label: "Riset kebijakan kolaborasi dengan pemerintah", type: "QUALITATIVE", weightInSdg: 6.4, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.3.4", label: "Platform netral untuk diskusi isu politik", type: "QUALITATIVE", weightInSdg: 4, maxScore: 3, subQuestions: STD_3PT },
    { code: "16.4.1", label: "Proporsi lulusan hukum dan penegakan hukum sipil", type: "QUANTITATIVE", weightInSdg: 23.2, metrics: [{ key: "totalGraduates", label: "16.4.1 Jumlah lulusan", unit: "orang" }, { key: "lawEnforcementGraduates", label: "16.4.1 Jumlah lulusan hukum dan penegakan hukum sipil", unit: "orang" }] },
  ]},
  17: { number: 17, title: "Partnerships for the Goals", emoji: "🤝", color: "#19486A", mandatory: true, indicators: [
    { code: "17.1.1", label: "Proporsi publikasi co-authored dengan negara berpenghasilan rendah/menengah-bawah", type: "BIBLIOMETRIC", weightInSdg: 13.55 },
    { code: "17.1.2", label: "Jumlah publikasi terkait Partnerships for the Goals (SDG 1-17)", type: "BIBLIOMETRIC", weightInSdg: 13.55 },
    { code: "17.2.1", label: "Keterlibatan dalam kebijakan SDG pemerintah/NGO regional", type: "QUALITATIVE", weightInSdg: 3.7, maxScore: 3, subQuestions: STD_3PT },
    { code: "17.2.2", label: "Dialog lintas sektor tentang SDGs", type: "QUALITATIVE", weightInSdg: 3.7, maxScore: 3, subQuestions: STD_3PT },
    { code: "17.2.3", label: "Kolaborasi internasional pengumpulan data SDGs", type: "QUALITATIVE", weightInSdg: 3.7, maxScore: 3, subQuestions: STD_3PT },
    { code: "17.2.4", label: "Kolaborasi internasional best practice SDGs", type: "QUALITATIVE", weightInSdg: 3.7, maxScore: 3, subQuestions: STD_3PT },
    { code: "17.2.5", label: "Kolaborasi dengan NGO untuk SDGs", type: "QUALITATIVE", weightInSdg: 3.7, maxScore: 3, subQuestions: STD_3PT },
    ...Array.from({ length: 17 }, (_, i) => ({
      code: `17.3.${i + 1}`,
      label: `Publikasi laporan SDG ${i + 1}`,
      type: "QUALITATIVE" as const,
      weightInSdg: 1.6,
      maxScore: 3,
      subQuestions: STD_3PT,
    })),
    { code: "17.4.1", label: "Komitmen pendidikan SDGs yang bermakna di seluruh universitas", type: "QUALITATIVE", weightInSdg: 9.06, maxScore: 3, subQuestions: STD_3PT },
    { code: "17.4.2", label: "Mata kuliah/program khusus keberlanjutan & SDGs", type: "QUALITATIVE", weightInSdg: 9.06, maxScore: 3, subQuestions: STD_3PT },
    { code: "17.4.3", label: "Kegiatan edukasi SDGs untuk komunitas luas", type: "QUALITATIVE", weightInSdg: 9.06, maxScore: 3, subQuestions: STD_3PT },
    { code: "17.4.4", label: "Pengukuran sustainability literacy mahasiswa (informasional, tidak diskor 2026)", type: "QUALITATIVE", weightInSdg: 0, maxScore: 3, subQuestions: STD_3PT },
  ]},
};

export const MANDATORY_SDGS = [1, 3, 4, 8, 17];

/** Answer shape for a QUALITATIVE indicator */
export interface QualAnswer {
  answered: "ya" | "tidak" | null;
  comment: string;
  publicLinks: string[];
  policyUpdated?: boolean;
  scopeCoverage?: "none" | "scope1_2" | "scope1_2_3_partial" | "scope1_2_3_full" | null;
  targetYear?: number | null;
}

/** Answer shape for a QUANTITATIVE indicator */
export type QuantAnswer = Record<string, string>;

/** Answer shape for a BIBLIOMETRIC indicator */
export interface BiblAnswer {
  score: number;
}

/** Full answer map for one SDG submission */
export type SdgAnswers = Record<string, QualAnswer | QuantAnswer | BiblAnswer>;
